### ISSUE TITLE
Verbose flag not set, still showing debug info.

### ISSUE THREAD

**Issue by aerth** [suntong/cloudmail#1]
```
user@gmail.com authenticated (Success)
server capabilities: [IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT LIST-EXTENDED LIST-STATUS APPENDLIMIT=35882577]
opening INBOX...
mailbox status: &{Flags:[\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing] Exists:150 Recent:0 PermanentFlags:[] UIDValidity:1 UIDNext:276}
requesting messages 1:150
complete OK [%!s(<nil>)] Success

```

**Comment by suntong** [comment]
This is more or less a personal preference issue, just like when system boots up, Windows tends to hide everything and *nix tends to show everything. Thus there is no right or wrong way of looking at it.

I personally agree with the original author in regarding that such messages are being as part of the progress report. I.e., transparency is much more important than hiding info to me.
